spring:
  application:
      name: websocket
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://jackiergleason.auth0.com/
          audiences:
            - https://billing.secondave.net
